# Generated by Django 3.2.7 on 2021-09-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insumos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('contenido', models.TextField(blank=True, null=True)),
                ('ingredientes', models.ManyToManyField(to='Insumos.Ingrediente')),
                ('ingredientesEsp', models.ManyToManyField(to='Insumos.IngredientesEsp')),
            ],
        ),
    ]
