# Generated by Django 3.2.7 on 2021-10-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insumos', '0002_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='unidades',
        ),
    ]
